use std::path::Path;
use anyhow::{Result, Context};
use crate::clipboard::ClipboardSink;

#[derive(Default)]
pub struct WindowsSink;

impl WindowsSink {
    pub fn new() -> Self {
        Self
    }
}

impl ClipboardSink for WindowsSink {
    fn put_image(&self, jpeg_bytes: &[u8]) -> Result<()> {
        let img = image::load_from_memory(jpeg_bytes)
            .context("Failed to decode JPEG bytes for clipboard writing")?;
        
        let rgba = img.to_rgba8();
        let (w, h) = rgba.dimensions();
        
        let mut ctx = arboard::Clipboard::new()
            .context("Failed to open system clipboard via arboard")?;
            
        let img_data = arboard::ImageData {
            width: w as usize,
            height: h as usize,
            bytes: std::borrow::Cow::Borrowed(&rgba),
        };
        
        ctx.set_image(img_data)
            .context("Failed to set image to system clipboard")?;
            
        tracing::info!("Successfully copied image to Windows clipboard via arboard");
        Ok(())
    }

    fn put_file(&self, path: &Path) -> Result<()> {
        let abs_path = std::fs::canonicalize(path)
            .context("Failed to resolve absolute path of target file")?;
            
        let file_path_str = abs_path.to_string_lossy().to_string();
        
        // Clean prefix if generated by standard Windows path canonicalization (e.g. \\?\)
        let clean_path = file_path_str.trim_start_matches(r#"\\?\"#).to_string();
        
        // Escape single quotes to prevent PowerShell command injection
        let escaped_path = clean_path.replace('\'', "''");
        let script = format!("Set-Clipboard -Path '{}'", escaped_path);
        
        let output = std::process::Command::new("powershell")
            .arg("-WindowStyle")
            .arg("Hidden")
            .arg("-Command")
            .arg(&script)
            .output()
            .context("Failed to execute PowerShell clipboard command")?;
            
        if output.status.success() {
            tracing::info!("Successfully copied file path (CF_HDROP) to Windows clipboard via PowerShell: {:?}", path);
            Ok(())
        } else {
            let err_msg = String::from_utf8_lossy(&output.stderr).to_string();
            Err(anyhow::anyhow!("PowerShell error setting clipboard: {}", err_msg))
        }
    }
}
